Restaurant/urls.py
from django.urls import path, include

from Restaurant import views
from rest_framework import routers
from .api_views import StudentAPIView, TicketAPIView, OrderAPIView, FoodAPIView, StudentTicketAPIView

app_name = 'Cafeteria'

router = routers.DefaultRouter()
router.register('student', StudentAPIView)
router.register('food', FoodAPIView)
router.register('ticket', TicketAPIView)
router.register('order', OrderAPIView)
router.register('student-ticket', StudentTicketAPIView)

urlpatterns = [
    path('', views.index, name="home"),
    path('register', views.student_registration, name="student_registration"),
    path('meal', views.meal_menu, name="meal_menu"),
    path('display-ticket', views.display_tickets, name="display_tickets"),
    path('generate-ticket', views.ticket_generator, name="ticket_generator"),
    path('generate-ticket/create', views.create_tickets, name="create_tickets"),
    path('confirm-order', views.confirm_order, name="confirm_order"),
    path('confirm-order/accept/<int:order_id>', views.accept_order, name="accept_order"),
    path('confirm-order/decline/<int:order_id>', views.decline_order, name="decline_order"),
    path('logout', views.log_out, name="logout"),
    path('api', include(router.urls))
]

Web_Cafe/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Web_Cafe import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Restaurant.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = "Restaurant.views.error_400"
handler403 = "Restaurant.views.error_403"
handler404 = "Restaurant.views.error_404"
handler500 = "Restaurant.views.error_500"

Restaurant/forms.py
from django import forms


class StudentForm(forms.Form):

    full_name = forms.CharField(
        max_length=250,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter Full Name',
                'required': '',
                'class': 'input',
            }
        )
    )

    student_id = forms.CharField(
        max_length=15,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter Student Id',
                'required': '',
                'class': 'input',
            }
        )
    )

    sex = forms.CharField(
        max_length=6,
        widget=forms.Select(
            choices=[('', 'Select Sex...'), ('M', 'Male'), ('F', 'Female')],
            attrs={
                'required': '',
                'class': 'input',
            }
        )
    )

    department = forms.CharField(
        max_length=250,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter Department',
                'required': '',
                'class': 'input',
            }
        )
    )

    def clean(self):
        cleaned_data = super(StudentForm, self).clean()
        full_name = cleaned_data.get('full_name')
        student_id = cleaned_data.get('student_id')
        sex = cleaned_data.get('sex')
        department = cleaned_data.get('department')

        if not student_id or not full_name or not sex or not department:
            raise forms.ValidationError('Field cannot be empty')


class FoodForm(forms.Form):
    food_name = forms.CharField(
        max_length=250,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter Food Name',
                'required': '',
                'class': 'input',
            }
        )
    )

    stock = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'required': '',
                'class': 'input',
            }
        )
    )

    def clean(self):
        cleaned_data = super(FoodForm, self).clean()
        food_name = cleaned_data.get('food_name')
        stock = cleaned_data.get('stock')

        if not food_name or not stock:
            raise forms.ValidationError('Field cannot be empty')


class OrderForm(forms.Form):
    ticket_id = forms.CharField(
        max_length=10,
        widget=forms.TextInput(
            attrs={
                'required': '',
                'class': 'input',
            }
        )
    )

    student_id = forms.CharField(
        max_length=15,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter Student Id',
                'required': '',
                'class': 'input',
            }
        )
    )

    food_name = forms.CharField(
        max_length=250,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter Food Name',
                'required': '',
                'class': 'input',
            }
        )
    )

    quantity = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'required': '',
                'class': 'input',
            }
        )
    )

    def clean(self):
        cleaned_data = super(OrderForm, self).clean()
        ticket_id = cleaned_data.get('ticket_id')
        student_id = cleaned_data.get('student_id')
        food_name = cleaned_data.get('food_name')
        quantity = cleaned_data.get('quantity')

        if not ticket_id or not student_id or not food_name or not quantity:
            raise forms.ValidationError('Field cannot be empty')


class ValidateTicketForm(forms.Form):
    ticket_id = forms.CharField(
        max_length=10,
        widget=forms.TextInput(
            attrs={
                'required': '',
                'class': 'input',
            }
        )
    )

    student_id = forms.CharField(
        max_length=15,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter Student Id',
                'required': '',
                'class': 'input',
            }
        )
    )

    def clean(self):
        cleaned_data = super(ValidateTicketForm, self).clean()
        ticket_id = cleaned_data.get('ticket_id')
        student_id = cleaned_data.get('student_id')

        if not ticket_id or not student_id:
            raise forms.ValidationError('Field cannot be empty')


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=250,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter Username',
                'required': '',
                'class': 'input',
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Enter password',
                'required': '',
                'class': 'input',
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if not username or not password:
            raise forms.ValidationError('field cannot be empty')

Restaurant/views.py
import string
import random

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone

from Restaurant.forms import LoginForm, ValidateTicketForm, OrderForm, StudentForm, FoodForm
from Restaurant.models import Student, StudentTicket, Food, Order, Ticket

random = random.Random()


def index(request):
    if request.user.is_authenticated and not request.user.is_superuser:
        if request.method == 'POST':
            form = OrderForm(request.POST)
            if form.is_valid():
                ticket_id = form.cleaned_data['ticket_id']
                student_id = form.cleaned_data['student_id'].upper()
                food_name = form.cleaned_data['food_name']
                quantity = form.cleaned_data['quantity']

                current_food = get_object_or_404(Food, name=food_name)

                if current_food.stock < quantity:
                    messages.error(request, "Quantity of {current_food.name} left is {current_food.quantity}")
                    return HttpResponseRedirect(reverse('Cafeteria:home'))
                elif current_food.stock == 0:
                    messages.error(request, "Meal unavailable")
                    return HttpResponseRedirect(reverse('Cafeteria:home'))

                all_student = Student.objects.all()
                for student in all_student:
                    if student_id == student.student_id:
                        current_student = get_object_or_404(Student, student_id=student_id)
                        current_student.save()
                        break
                else:
                    messages.error(request, "Student does not exist")

                all_ticket = Ticket.objects.all()
                for ticket in all_ticket:
                    if ticket_id == ticket.serial_no:
                        current_ticket = get_object_or_404(Ticket, serial_no=ticket_id)
                        current_ticket.save()

                        if not current_ticket.is_valid:
                            messages.error(request, "Ticket already used")
                            return HttpResponseRedirect(reverse('Cafeteria:home'))
                        elif (timezone.now() - current_ticket.date) > timezone.timedelta(hours=24):
                            messages.error(request, "Ticket already outdated")
                            return HttpResponseRedirect(reverse('Cafeteria:home'))
                        break

                else:
                    messages.error(request, "Ticket does not exist")

                current_student_ticket = get_object_or_404(StudentTicket, student=current_student)
                current_student_ticket.save()

                for ticket in current_student_ticket.ticket.all():
                    if ticket_id == ticket.serial_no:
                        current_order = Order.objects.create(student=current_student, food=current_food,
                                                             ticket=current_ticket, quantity=quantity,
                                                             date=timezone.now())
                        current_order.save()
                        return render(request, 'restaurant/confirm_order.html', {'current_order': current_order})
                else:
                    messages.error(request, "Ticket input is not allocated to the student")
                    return HttpResponseRedirect(reverse('Cafeteria:home'))
        else:
            form = OrderForm()
        return render(request, 'restaurant/order.html', {'form': form})
    else:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user = authenticate(request, username=username, password=password)
                if user is not None and not user.is_superuser:
                    login(request, user)
                    return HttpResponseRedirect(reverse('Cafeteria:home'))
                else:
                    messages.error(request, "Invalid login details")
                    return HttpResponseRedirect(reverse('Cafeteria:home'))

        else:
            form = LoginForm()
        return render(request, 'restaurant/index.html', {'form': form})


def confirm_order(request):
    if request.user.is_authenticated and not request.user.is_superuser:
        messages.success(request, "Meal successfully ordered")
        return render(request, 'restaurant/confirm_order.html')
    else:
        messages.error(request, "Kindly login please")
        return HttpResponseRedirect(reverse('Cafeteria:home'))


def accept_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.is_verified = True
    order.ticket.is_valid = False
    order.ticket.save()
    order.save()

    food = order.food
    food.stock -= order.quantity
    food.save()

    current_student_ticket = get_object_or_404(StudentTicket, student=order.student)
    current_student_ticket.ticket.remove(order.ticket)
    current_student_ticket.save()

    return HttpResponseRedirect(reverse('Cafeteria:home'))


def decline_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.delete()
    return HttpResponseRedirect(reverse('Cafeteria:home'))


def student_registration(request):
    if request.user.is_authenticated and not request.user.is_superuser:
        if request.method == 'POST':
            form = StudentForm(request.POST)
            if form.is_valid():
                full_name = form.cleaned_data['full_name'].strip().upper()
                student_id = form.cleaned_data['student_id'].strip().upper()
                sex = form.cleaned_data['sex'].strip()
                department = form.cleaned_data['department'].strip().upper()
                all_student = Student.objects.all()
                for student in all_student:
                    if student_id == student.student_id:
                        messages.error(request, "Student already exists, kindly input the correct information")
                        return HttpResponseRedirect(reverse('Cafeteria:student_registration'))
                else:
                    Student.objects.create(full_name=full_name, student_id=student_id, sex=sex, department=department)
                    messages.success(request, "Student successfully registered")
                    return HttpResponseRedirect(reverse('Cafeteria:home'))

        else:
            form = StudentForm()
        return render(request, 'restaurant/register.html', {'form': form})
    else:
        messages.error(request, "Kindly login please")
        return HttpResponseRedirect(reverse('Cafeteria:home'))


def meal_menu(request):
    if request.user.is_authenticated and not request.user.is_superuser:
        if request.method == 'POST':
            form = FoodForm(request.POST)
            if form.is_valid():
                food_name = form.cleaned_data['food_name']
                stock = form.cleaned_data['stock']

                all_food = Food.objects.all()
                for food in all_food:
                    if food_name == food.name:
                        messages.error(request, "Meal already available in the menu")
                        return HttpResponseRedirect(reverse('Cafeteria:meal_menu'))
                else:
                    Food.objects.create(name=food_name, stock=stock, date=timezone.now())
                    messages.success(request, "Meal added successfully")
                    return HttpResponseRedirect(reverse('Cafeteria:meal_menu'))

        else:
            form = FoodForm()
        return render(request, 'restaurant/meal_menu.html', {'form': form})
    else:
        messages.error(request, "Kindly login please")
        return HttpResponseRedirect(reverse('Cafeteria:home'))


def ticket_generator(request):
    if request.user.is_authenticated and not request.user.is_superuser:
        return render(request, 'restaurant/ticket_generator.html')
    else:
        messages.error(request, "Kindly login please")
        return HttpResponseRedirect(reverse('Cafeteria:home'))


def create_tickets(request):
    all_students = Student.objects.all()
    all_tickets = Ticket.objects.all()
    for student in all_students:
        current_student_ticket = StudentTicket.objects.create(student=student)
        NUMBER_OF_TICKETS = 0
        while NUMBER_OF_TICKETS < 2:
            serial_no = ''.join([random.choice(string.digits) for i in range(10)])
            for ticket in all_tickets:
                if serial_no == ticket.serial_no:
                    break
            else:
                ticket = Ticket.objects.create(serial_no=serial_no, date=timezone.now())
                current_student_ticket.ticket.add(ticket)
                NUMBER_OF_TICKETS += 1

    messages.success(request, "Tickets successfully generated")
    return HttpResponseRedirect(reverse('Cafeteria:home'))


def display_tickets(request):
    all_tickets = StudentTicket.objects.all()
    if request.user.is_authenticated and not request.user.is_superuser:
        return render(request, 'restaurant/tickets.html', {'all_tickets': all_tickets})
    else:
        messages.error(request, "Kindly login please")
        return HttpResponseRedirect(reverse('Cafeteria:home'))


def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('Cafeteria:home'))


def error_400(request, exception):
    return render(request, 'restaurant/error_page.html')


def error_403(request, exception):
    return render(request, 'restaurant/error_page.html')


def error_404(request, exception):

Restaurant/templates/restaurant/confirm_order.html
{% extends 'base.html' %}

{% block title %}
<title>Confirm Order</title>
{% endblock %}

{% block header %}
<div class="px-3 py-2 border-bottom mb-3">
    <div class="container d-flex flex-wrap justify-content-center">
        <div class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto">
            <h3 class="fw-bold">CONFIRM ORDER</h3>
        </div>

        <div class="text-end">
            <a href="{% url 'Cafeteria:logout' %}" type="button" class="btn btn-danger">Logout</a>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

{% for message in messages %}
{% if message.tags == "success" %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-6">
            <article class="message is-success">
                <div class="message-header">
                    <p>Success</p>
                    <button class="delete" aria-label="delete"></button>
                </div>
                <div class="message-body">
                    <em>{{ message }}</em>
                </div>
            </article>
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-6">
            <article class="message is-danger">
                <div class="message-header">
                    <p>Error</p>
                    <button class="delete" aria-label="delete"></button>
                </div>
                <div class="message-body">
                    <em>{{ message }}</em>
                </div>
            </article>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}

<div class="container pt-6">
    <div class="row d-flex justify-content-center">
        <div class="col-md-5 col-lg-8 order-md-last">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-primary fw-bold">Your Order</span>
                <span class="badge bg-primary rounded-pill"></span>
            </h4>
            <ul class="list-group mb-3">
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0 fw-bold">Student Name</h6>
                        <small class="text-muted"></small>
                    </div>
                    <span class="text-muted">{{ current_order.student.full_name }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0 fw-bold">Student Id</h6>
                        <small class="text-muted"></small>
                    </div>
                    <span class="text-muted">{{ current_order.student.student_id }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0 fw-bold">Meal</h6>
                        <small class="text-muted"></small>
                    </div>
                    <span class="text-muted">{{ current_order.food.name }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0 fw-bold">Ticket Id</h6>
                        <small class="text-muted"></small>
                    </div>
                    <span class="text-muted">{{ current_order.ticket.serial_no }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0 fw-bold">Quantity</h6>
                        <small class="text-muted"></small>
                    </div>
                    <span class="text-muted">{{ current_order.quantity }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0 fw-bold">Date</h6>
                        <small class="text-muted"></small>
                    </div>
                    <span class="text-muted">{{ current_order.date }}</span>
                </li>
            </ul>

            <div class="card p-2">
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div class="input-group">
                    <a href="{% url 'Cafeteria:accept_order' current_order.id%}" type="button" class="btn btn-success">Accept</a>
                </div>
                    <span class="text-muted"><a href="{% url 'Cafeteria:decline_order' current_order.id%}" type="button" class="btn btn-danger">Decline</a></span>
                </li>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Restaurant/templates/restaurant/django_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
</div>
{% endif %}

{% for field in form.visible_fields %}
<div class="field">
    <label class="label">{{ field.label_tag }} </label>

    <div class="control">
        {% if form.is_bound %}
        {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
    </div>
    {% for error in field.errors %}
    <div class="invalid-feedback">
        {{ error }}
    </div>
    {% endfor %}
    <div class="control">
        {% else %}
        {% render_field field class="form-control is-valid" %}
        {% endif %}
        {% else %}
        {% render_field field class="form-control" %}
        {% endif %}
    </div>

    {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text }} <small style="color: red">*</small></small>
    {% endif %}
</div>
{% endfor %}

Restaurant/templates/restaurant/error_page.html
{% extends 'base.html' %}

{% block title %}
<title>Place Order</title>
{% endblock %}

{% block header %}
<div class="px-3 py-2 border-bottom mb-3">
    <div class="container d-flex flex-wrap justify-content-center">
        <div class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto">
            <h3 class="fw-bold">PLACE ORDER</h3>
        </div>

        <div class="text-end">
          <a href="{% url 'Cafeteria:logout' %}" type="button" class="btn btn-danger">Logout</a>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

{% for message in messages %}
{% if message.tags == "success" %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-6">
            <article class="message is-success">
                <div class="message-header">
                    <p>Success</p>
                    <button class="delete" aria-label="delete"></button>
                </div>
                <div class="message-body">
                    <em>{{ message }}</em>
                </div>
            </article>
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-6">
            <article class="message is-danger">
                <div class="message-header">
                    <p>Error</p>
                    <button class="delete" aria-label="delete"></button>
                </div>
                <div class="message-body">
                    <em>{{ message }}</em>
                </div>
            </article>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}

<div class="container pt-6">
    <div class="row d-flex justify-content-center">
        <h1>WRONG REQUEST</h1>
        <small>There must have been an error...</small>
    </div>
</div>
{% endblock %}

Restaurant/templates/restaurant/meal_menu.html
{% extends 'base.html' %}

{% block title %}
<title>Meal Menu</title>
{% endblock %}

{% block header %}
<div class="px-3 py-2 border-bottom mb-3">
    <div class="container d-flex flex-wrap justify-content-center">
        <div class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto">
            <h3 class="fw-bold">MEAL MENU</h3>
        </div>

        <div class="text-end">
          <a href="{% url 'Cafeteria:logout' %}" type="button" class="btn btn-danger">Logout</a>
        </div>
    </div>
</div>
{% endblock %}


{% block content %}

{% for message in messages %}
{% if message.tags == "success" %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-6">
            <article class="message is-success">
                <div class="message-header">
                    <p>Success</p>
                    <button class="delete" aria-label="delete"></button>
                </div>
                <div class="message-body">
                    <em>{{ message }}</em>
                </div>
            </article>
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-6">
            <article class="message is-danger">
                <div class="message-header">
                    <p>Error</p>
                    <button class="delete" aria-label="delete"></button>
                </div>
                <div class="message-body">
                    <em>{{ message }}</em>
                </div>
            </article>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}

<div class="container pt-6 pb-6 mb-6">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-6">
            <form action="" method="post">
                {% csrf_token %}
                <div class="account__form" style="border:0">
                    {% include 'restaurant/django_form.html' with form=form %}
                    <div>
                        <button class="button is-fullwidth is-rounded is-info label" type="submit">Submit
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Restaurant/templates/restaurant/order.html
{% extends 'base.html' %}

{% block title %}
<title>Place Order</title>
{% endblock %}

{% block header %}
<div class="px-3 py-2 border-bottom mb-3">
    <div class="container d-flex flex-wrap justify-content-center">
        <div class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto">
            <h3 class="fw-bold">PLACE ORDER</h3>
        </div>

        <div class="text-end">
          <a href="{% url 'Cafeteria:logout' %}" type="button" class="btn btn-danger">Logout</a>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

{% for message in messages %}
{% if message.tags == "success" %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-6">
            <article class="message is-success">
                <div class="message-header">
                    <p>Success</p>
                    <button class="delete" aria-label="delete"></button>
                </div>
                <div class="message-body">
                    <em>{{ message }}</em>
                </div>
            </article>
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-6">
            <article class="message is-danger">
                <div class="message-header">
                    <p>Error</p>
                    <button class="delete" aria-label="delete"></button>
                </div>
                <div class="message-body">
                    <em>{{ message }}</em>
                </div>
            </article>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}

<div class="container pt-6">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-6">
            <form action="" method="post">
                {% csrf_token %}
                <div class="account__form" style="border:0">
                    {% include 'restaurant/django_form.html' with form=form %}
                    <div>
                        <button class="button is-fullwidth is-rounded is-info label" type="submit">Submit
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Restaurant/templates/restaurant/ticket_generator.html
{% extends 'base.html' %}

{% block title %}
<title>Ticket Generator</title>
{% endblock %}

{% block header %}
<div class="px-3 py-2 border-bottom mb-3">
    <div class="container d-flex flex-wrap justify-content-center">
        <div class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto">
            <h3 class="fw-bold">TICKET GENERATOR</h3>
        </div>

        <div class="text-end">
          <a href="{% url 'Cafeteria:logout' %}" type="button" class="btn btn-danger">Logout</a>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

{% for message in messages %}
{% if message.tags == "success" %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-6">
            <article class="message is-success">
                <div class="message-header">
                    <p>Success</p>
                    <button class="delete" aria-label="delete"></button>
                </div>
                <div class="message-body">
                    <em>{{ message }}</em>
                </div>
            </article>
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-6">
            <article class="message is-danger">
                <div class="message-header">
                    <p>Error</p>
                    <button class="delete" aria-label="delete"></button>
                </div>
                <div class="message-body">
                    <em>{{ message }}</em>
                </div>
            </article>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}

<div class="px-4 py-5 my-5 pb-6 mb-6 text-center">
    <div class="col-lg-6 mx-auto">
      <p class="display-6 fw-bold mb-3">Tickets are automatically generated for our workers on a daily basis through the click of a button.</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a href="{% url 'Cafeteria:create_tickets' %}" type="button" class="btn btn-primary btn-lg px-4 gap-3">Generate Tickets</a>
      </div>
    </div>
  </div>
{% endblock %}