Restaurant/urls.py
from django.urls import path, include

from Restaurant import views
from rest_framework import routers
from .api_views import StudentAPIView, TicketAPIView, OrderAPIView, FoodAPIView, StudentTicketAPIView

app_name = 'Cafeteria'

router = routers.DefaultRouter()
router.register('student', StudentAPIView)
router.register('food', FoodAPIView)
router.register('ticket', TicketAPIView)
router.register('order', OrderAPIView)
router.register('student-ticket', StudentTicketAPIView)

urlpatterns = [
    path('', views.index, name="home"),
    path('register', views.student_registration, name="student_registration"),
    path('meal', views.meal_menu, name="meal_menu"),
    path('display-ticket', views.display_tickets, name="display_tickets"),
    path('generate-ticket', views.ticket_generator, name="ticket_generator"),
    path('generate-ticket/create', views.create_tickets, name="create_tickets"),
    path('confirm-order', views.confirm_order, name="confirm_order"),
    path('confirm-order/accept/<int:order_id>', views.accept_order, name="accept_order"),
    path('confirm-order/decline/<int:order_id>', views.decline_order, name="decline_order"),
    path('logout', views.log_out, name="logout"),
    path('api', include(router.urls))
]

Web_Cafe/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Web_Cafe import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Restaurant.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = "Restaurant.views.error_400"
handler403 = "Restaurant.views.error_403"
handler404 = "Restaurant.views.error_404"
handler500 = "Restaurant.views.error_500"

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Mochiy+Pop+P+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

    {% block title %}
    {% endblock %}

</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="bootstrap" viewBox="0 0 118 94">
        <title>Bootstrap</title>
        <path fill-rule="evenodd" clip-rule="evenodd"
              d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
    </symbol>
    <symbol id="home" viewBox="0 0 16 16">
        <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"></path>
    </symbol>
    <symbol id="speedometer2" viewBox="0 0 16 16">
        <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"></path>
        <path fill-rule="evenodd"
              d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"></path>
    </symbol>
    <symbol id="table" viewBox="0 0 16 16">
        <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"></path>
    </symbol>
    <symbol id="people-circle" viewBox="0 0 16 16">
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
        <path fill-rule="evenodd"
              d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"></path>
    </symbol>
    <symbol id="grid" viewBox="0 0 16 16">
        <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"></path>
    </symbol>
</svg>

<main>
    <header>
        <div class="px-3 py-2 bg-dark text-white">
            <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                    <a href="{% url 'Cafeteria:home' %}"
                       class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none col-4">
                        <h1 class="display-6 fw-bold">Kings And Queens Cafeteria</h1>
                    </a>

                    <nav class="navbar navbar-expand-sm navbar-dark col-8 justify-content-end" style="background: inherit">
                        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                          </button>
                        <div class="container-fluid">
                            <div class="collapse navbar-collapse" id="navbar">
                                <ul class="nav col-8 col-lg-auto my-2 justify-content-center my-md-0 text-small"
                                    style="border-color: grey; border-style: solid; border-radius: 3%; background-color: green">
                                    <li>
                                        <a href="{% url 'Cafeteria:student_registration' %}"
                                           class="nav-link text-white">
                                            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
                                                <use xlink:href="#people-circle"></use>
                                            </svg>
                                            Student Registration
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'Cafeteria:ticket_generator' %}" class="nav-link text-white">
                                            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
                                                <use xlink:href="#table"></use>
                                            </svg>
                                            Generate Ticket
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'Cafeteria:meal_menu' %}" class="nav-link text-white">
                                            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
                                                <use xlink:href="#grid"></use>
                                            </svg>
                                            Meal Menu
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'Cafeteria:home' %}" class="nav-link text-white">
                                            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
                                                <use xlink:href="#table"></use>
                                            </svg>
                                            Order
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'Cafeteria:display_tickets' %}" class="nav-link text-white">
                                            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
                                                <use xlink:href="#grid"></use>
                                            </svg>
                                            Tickets
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        {% block header %}
        {% endblock %}
    </header>
</main>

{% block content %}
{% endblock %}

<section>
    <div class="b-example-divider"></div>
    <div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">© 2022 Kings And Queens Cafeteria</p>

    <ul class="nav justify-content-center pb-3 mb-3">
      <li class="nav-item"><a href="{% url 'Cafeteria:student_registration' %}" class="nav-link px-2 text-muted">Student Registration</a></li>
      <li class="nav-item"><a href="{% url 'Cafeteria:ticket_generator' %}" class="nav-link px-2 text-muted">Generate Ticket</a></li>
      <li class="nav-item"><a href="{% url 'Cafeteria:meal_menu' %}" class="nav-link px-2 text-muted">Meal Menu</a></li>
      <li class="nav-item"><a href="{% url 'Cafeteria:home' %}" class="nav-link px-2 text-muted">Order</a></li>
        <li class="nav-item"><a href="{% url 'Cafeteria:display_tickets' %}" class="nav-link px-2 text-muted">Ticket</a></li>
    </ul>
  </footer>
</div>
    <div class="b-example-divider"></div>
</section>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>